# Generated by Django 4.1.5 on 2023-02-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Have',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500)),
                ('title', models.CharField(max_length=100)),
                ('condition', models.IntegerField(choices=[(1, 'New'), (2, 'Used Like New'), (3, 'Used Good'), (4, 'Used Fair')])),
                ('wants_for_this_item', models.CharField(blank=True, max_length=200)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
