# Generated by Django 4.1.5 on 2023-02-06 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0001_initial'),
        ('have', '0001_initial'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='have',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='haves', to='user_profile.userprofile'),
        ),
        migrations.AddField(
            model_name='have',
            name='tags',
            field=models.ManyToManyField(related_name='haves', to='tag.tag'),
        ),
    ]
