# Generated by Django 4.1.5 on 2023-02-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('have', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='have',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Pending'), (3, 'Not Active'), (4, 'Gone')], default=1),
            preserve_default=False,
        ),
    ]
