# Generated by Django 4.1.5 on 2023-01-31 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('want', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('want', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='want.want')),
            ],
        ),
    ]
