# Generated by Django 4.1.5 on 2023-02-06 18:37

from django.db import migrations, models
import django.db.models.deletion
import want_image.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('want', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to=want_image.models.post_directory_path)),
                ('want', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='want.want')),
            ],
        ),
    ]
