# Generated by Django 4.1.5 on 2023-02-04 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('want', '0002_rename_user_profile_want_author'),
        ('want_image', '0002_wantimage_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wantimage',
            name='want',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='want.want'),
        ),
    ]
