# Generated by Django 4.1.5 on 2023-02-04 08:31

from django.db import migrations, models
import have_image.models


class Migration(migrations.Migration):

    dependencies = [
        ('have_image', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='haveimage',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=have_image.models.post_directory_path),
        ),
    ]
