# Generated by Django 4.1.5 on 2023-01-31 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('message', '0001_initial'),
        ('user_profile', '0001_initial'),
        ('want', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='user_profile.userprofile'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='user_profile.userprofile'),
        ),
        migrations.AddField(
            model_name='message',
            name='want',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='want.want'),
        ),
    ]
