# Generated by Django 4.1.5 on 2023-02-06 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('have', '0002_initial'),
        ('user_profile', '0001_initial'),
        ('message', '0001_initial'),
        ('want', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='user_profile.userprofile'),
        ),
        migrations.AddField(
            model_name='message',
            name='receiver_have',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages_for_have', to='have.have'),
        ),
        migrations.AddField(
            model_name='message',
            name='receiver_want',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages_for_want', to='want.want'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='user_profile.userprofile'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_have',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages_for_have', to='have.have'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_want',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages_for_want', to='want.want'),
        ),
    ]
