# Generated by Django 4.1.5 on 2023-02-02 12:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
