# Generated by Django 4.1.5 on 2023-02-02 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
        ('message', '0003_message_created_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.AddField(
            model_name='message',
            name='receiver_has',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='received_message_for_has', to='user_profile.userprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='receiver_wants',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='received_message_for_want', to='user_profile.userprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='sender_has',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sent_message_for_has', to='user_profile.userprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='sender_wants',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sent_message_for_want', to='user_profile.userprofile'),
            preserve_default=False,
        ),
    ]
