# Generated by Django 4.1.5 on 2023-02-02 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
        ('message', '0004_remove_message_receiver_remove_message_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='receiver_has',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_message_for_has', to='user_profile.userprofile'),
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver_wants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_message_for_want', to='user_profile.userprofile'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_has',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_message_for_has', to='user_profile.userprofile'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_wants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_message_for_want', to='user_profile.userprofile'),
        ),
    ]
