# Generated by Django 4.1.5 on 2023-02-02 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
        ('have', '0003_rename_user_profile_have_author'),
        ('want', '0002_rename_user_profile_want_author'),
        ('message', '0005_alter_message_receiver_has_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='have',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiver_has',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiver_wants',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender_has',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender_wants',
        ),
        migrations.RemoveField(
            model_name='message',
            name='want',
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='user_profile.userprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='receiver_have',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages_for_have', to='have.have'),
        ),
        migrations.AddField(
            model_name='message',
            name='receiver_want',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages_for_want', to='want.want'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='user_profile.userprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='sender_have',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages_for_have', to='have.have'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_want',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages_for_want', to='want.want'),
        ),
    ]
