# Generated by Django 4.1.5 on 2023-02-06 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0001_initial'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Want',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500)),
                ('title', models.CharField(max_length=100)),
                ('condition', models.IntegerField(blank=True, choices=[(1, 'New'), (2, 'Used Like New'), (3, 'Used Good'), (4, 'Used Fair')])),
                ('has_for_this_item', models.CharField(blank=True, max_length=200)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wants', to='user_profile.userprofile')),
                ('tags', models.ManyToManyField(related_name='wants', to='tag.tag')),
            ],
        ),
    ]
